### ISSUE TITLE
Prebuild image link is dead

### ISSUE THREAD

**Issue by pbk20191** [nick-petrovsky/PYNQ-ZYBO#1] opened 2024-02-19 14:39 UTC
Hello, first of all.
I'm really happy to discover this project and it's very helpful.
It looks like the link to the pre-build image has been corrupted.
Could you get the link back?

**Comment by nick-petrovsky** [comment] 2024-02-20 12:55
Hello! Thank for your interest, please check [release tab](https://github.com/nick-petrovsky/PYNQ-ZYBO/releases/tag/v0.1.0) of the project.

**Comment by pbk20191** [comment] 2024-02-23 12:09
Thanks for fast response. I tried prebuilt image using balenaEtcher and it isn't working at all. 
- Can't connect the device using serial port
- led is not flashing at all ( is this intended?, pynq 2.7 disk image does flash leds )
- Can't access to the jupyter notebook

**Comment by nick-petrovsky** [comment] 2024-02-23 12:54
> Thanks for fast response. I tried prebuilt image using balenaEtcher and it isn't working at all.
> 
> * Can't connect the device using serial port
> * led is not flashing at all ( is this intended?, pynq 2.7 disk image does flash leds )
> * Can't access to the jupyter notebook

Are you sure that board you have is **old** Digilent Zybo? They actually have 3 variants:

- Zybo B.3 soc: zynq7010 (first Zybo with VGA, on official site it is marked as absolute, I have such one)
- Zybo Z7 soc: zynq7010 (I've not ported PYNQ for it yet, schematic is different a bit, image isn't compatible with it)
- Zybo Z7 soc: zynq7020 (same as previous but with bigger SoC)

If board part is correct, please check cables, power pin, boot pin configuration (set it to `SD`), and SDcard have to be at least 8GB (Probably 16 GB is more convenient).

Also check MD5sum of downloaded file:
```bash
$ md5sum Zybo-3.0.1-fix-boot-bin-fix-havege.img.xz
ef7fd9fbcd1dc035c02347687127a44d *Zybo-3.0.1-fix-boot-bin-fix-havege.img.xz
```

After kernel boot led `MI07` have to start blinking and you can try to ping it `192.168.2.99`, also embedded Linux correctly handle DHCP, so you can access jupyter and etc.

**Comment by pbk20191** [comment] 2024-02-23 14:00
Oh... wait my board is Zybo-Z7 (7020). So I was doing with the wrong solution. 
Thanks for reminding me.

**Comment by nick-petrovsky** [comment] 2024-03-05 09:16
> Oh... wait my board is Zybo-Z7 (7020). So I was doing with the wrong solution. Thanks for remining me.

I've managed to port this project to Zybo Z7-10, after few days I'll publish the image. Look like Zybo Z7-20 have same schematic and I can just change SoC part in TCL scripts. I'll kindly ask you to test the result.

**Comment by nick-petrovsky** [comment] 2024-03-09 21:25
> Oh... wait my board is Zybo-Z7 (7020). So I was doing with the wrong solution. Thanks for remining me.

Can you test the image for [Zybo-Z7-20](https://github.com/nick-petrovsky/PYNQ-ZYBO/releases/download/v0.1.0/Zybo-Z7-20-3.0.1-fix-havege.img.xz)?

**Comment by pbk20191** [comment] 2024-04-10 06:31
sorry for late response. i have just tested the image.
BaseOverlay leds blink on boot. But some system fails to start on boot.
<img width="208" alt="image" src="https://github.com/nick-petrovsky/PYNQ-ZYBO/assets/29122714/44b54a85-ea79-4f50-8b18-b41f270bdf94">

I can not restart `isc-dhcp-server.service` and `isc-dhcp-server6.service`. `jupyter.service` and `ifup@eth0.service` sometimes failed to start on boot.

on boot there is log about interrupt
```
zocl-drm axi:zyxclmm_drm: IRQ index 0 not found
```

I will attach log about the services.
[status.txt](https://github.com/nick-petrovsky/PYNQ-ZYBO/files/14928018/status.txt)


BaseOverlay leds works but switch and button does not responding.

**Comment by pbk20191** [comment] 2024-04-10 14:58
oh wait 

> sorry for late response. i have just tested the image. BaseOverlay leds blink on boot. But some system fails to start on boot. <img alt="image" width="208" src="https://private-user-images.githubusercontent.com/29122714/321112420-44b54a85-ea79-4f50-8b18-b41f270bdf94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NjEzNjksIm5iZiI6MTcxMjc2MTA2OSwicGF0aCI6Ii8yOTEyMjcxNC8zMjExMTI0MjAtNDRiNTRhODUtZWE3OS00ZjUwLThiMTgtYjQxZjI3MGJkZjk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDE0NTc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwYjJmN2I2Yzg3NDlmZWE4ZmJlYTBiMTk5ZTM4NjI5OTEzNWUyY2JlYTk2YTgyZWEzNGRiZGU1ZDI1NDc3ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yEfQxRC8PANLPO0UkLNdlWN9_Kj4gxVuD0986QmHZGo">
> 
> I can not restart `isc-dhcp-server.service` and `isc-dhcp-server6.service`. `jupyter.service` and `ifup@eth0.service` sometimes failed to start on boot.
> 
> on boot there is log about interrupt
> 
> ```
> zocl-drm axi:zyxclmm_drm: IRQ index 0 not found
> ```
> 
> I will attach log about the services. [status.txt](https://github.com/nick-petrovsky/PYNQ-ZYBO/files/14928018/status.txt)
> 
> BaseOverlay leds works but switch and button does not responding.

I checked again and BaseOverlay buttons and switch works normally.

**Comment by nick-petrovsky** [comment] 2024-04-18 07:39
> sorry for late response. i have just tested the image. BaseOverlay leds blink on boot. But some system fails to start on boot. <img alt="image" width="208" src="https://private-user-images.githubusercontent.com/29122714/321112420-44b54a85-ea79-4f50-8b18-b41f270bdf94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjQ5OTUsIm5iZiI6MTcxMzQyNDY5NSwicGF0aCI6Ii8yOTEyMjcxNC8zMjExMTI0MjAtNDRiNTRhODUtZWE3OS00ZjUwLThiMTgtYjQxZjI3MGJkZjk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA3MTgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4YmM3MzRjZTlhZjMxYjZiM2ViYTc2M2U1MjA1NmQ5MWMwNzQxMGVlNWQwZWUyZmMwMjhkMWFiYzZlZmIxOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HjERwE8CZVRnE7TiYJwyE0LJ_MHk6G6xuugOWcvuKYI">
> 
> I can not restart `isc-dhcp-server.service` and `isc-dhcp-server6.service`. `jupyter.service` and `ifup@eth0.service` sometimes failed to start on boot.
> 
> on boot there is log about interrupt
> 
> ```
> zocl-drm axi:zyxclmm_drm: IRQ index 0 not found
> ```
> 
> I will attach log about the services. [status.txt](https://github.com/nick-petrovsky/PYNQ-ZYBO/files/14928018/status.txt)
> 
> BaseOverlay leds works but switch and button does not responding.

Working leds and buttons is sign that PL image is seems to be correct.

This issue related to original Ubuntu rootfs that used in PYNQ project. I can confirm that  ISC DHCP IPv4/IPv6 server hasn't started properly, but you can safely ignore this error. Network interface eth0 configured by `networked` and `dhclient` without any issues, you should have a static IP `192.168.2.99` and DHCP-lease from router.

I faced with issues related to `jupyter.service` if board was rebooted before first boot completed, some files are corrupted or not properly coped etc.

Try to refresh SD and give some time until board completely boot. Please test ethernet with `ip a` and pinning some host, check that MAC is volatile after cold reboot. 

If you not facing with any other issues I will close the issue and mark z7020 image as correct. Thank you for testing!

**Comment by pbk20191** [comment] 2024-04-20 09:56
1. I checked static Ip and the other ip is valid for ssh and jupyter
2. jupyter.service and the other serivces might fail to start at the very first time. But I if I restart it manually, it will works normally (of course including next boot). Maybe it was rebooted too early by my loose cable? Like what you said. 
4. I checked the MAC and it has stable address, even after multiple cold reboot. (If I'm correct, you want me to check if MAC address is stable, right?)

**Comment by nick-petrovsky** [comment] 2024-09-19 10:43
> 1. I checked static Ip and the other ip is valid for ssh and jupyter

It should have both static and dynamic IP if DHCP is provided in network segment. Mentioned behaviour is expected. Unfortunately Jupyter isn't bind on ipv6 address group and overlapping subnets can happens even if ipv6 is configured correctly.

> 2. jupyter.service and the other serivces might fail to start at the very first time. But I if I restart it manually, it will works normally (of course including next boot). Maybe it was rebooted too early by my loose cable? Like what you said.

Probably. PYNQ is too fragile, especially during first boot.

> 3. I checked the MAC and it has stable address, even after multiple cold reboot. (If I'm correct, you want me to check if MAC address is stable, right?)

Right. This is was main idea why I contributed to this repo for old Zybo.

In my point of view, issue can be marked as resolved. So I can mark Zybo-Z7-20 as ''tested''.

**Closed as completed by nick-petrovsky** 2024-09-19 10:43 UTC
